#!/usr/bin/env python3
"""Build a standalone gzip-data static site without publishing it."""
from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor
import gzip
import hashlib
import json
from pathlib import Path
import re
import shutil
import sys
import tempfile

import version_frontend

ROOT = Path(__file__).resolve().parents[2]
REPORT = '.stats401-site-build.json'
GENERATOR = 'stats401-build-site-v1'
MAX_BYTES = 1_000_000_000  # Conservative decimal 1 GB, including the build report.


def sha256(path):
    digest = hashlib.sha256()
    with path.open('rb') as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b''):
            digest.update(block)
    return digest.hexdigest()


def json_text(value):
    return json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + '\n'


def regular_source(path, root):
    if not path.is_file() or not path.resolve().is_relative_to(root):
        raise ValueError(f'Missing or external source file: {path}')
    current = path
    while current != root:
        if current.is_symlink():
            raise ValueError(f'Source symlinks are unsupported: {path}')
        current = current.parent


def copy_assets(root, stage):
    for folder in ('view', 'data/lang', 'data/img'):
        source = root / folder
        if not source.is_dir():
            raise ValueError(f'Missing source directory: {source}')
        for path in sorted(source.rglob('*')):
            relative = path.relative_to(root)
            if 'tests' in relative.parts or '__pycache__' in relative.parts or path.name == '.DS_Store':
                continue
            if path.is_symlink():
                raise ValueError(f'Source symlinks are unsupported: {path}')
            if path.is_file():
                regular_source(path, root)
                target = stage / relative
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(path, target)
    if not (stage / 'data/img/media.json').is_file():
        raise ValueError('Required media manifest is data/img/media.json')


def frontend_csv_files(root):
    names = set()
    for path in sorted((root / 'view').rglob('*.js')):
        if 'tests' not in path.relative_to(root / 'view').parts:
            names.update(re.findall(r'''\bfetchCsv\(\s*['"]([a-z0-9_]+\.csv)['"]''', path.read_text()))
    if not names:
        raise ValueError('No literal frontend fetchCsv calls found; review the data-loading contract.')
    constants = (root / 'view/utils/constants.js').read_text()
    if not re.search(r'''\bDATASET\s*=\s*['"]processed['"]''', constants):
        raise ValueError('Site builds require the frontend DATASET to be processed.')
    return sorted(names)


def compress_csv(job):
    source, target, root = job
    regular_source(source, root)
    before = source.stat()
    digest = hashlib.sha256()
    target.parent.mkdir(parents=True, exist_ok=True)
    with source.open('rb') as stream, target.open('wb') as output:
        # Empty embedded filename and fixed mtime make the gzip bytes repeatable.
        with gzip.GzipFile(filename='', mode='wb', fileobj=output, compresslevel=9, mtime=0) as compressed:
            for block in iter(lambda: stream.read(1024 * 1024), b''):
                digest.update(block)
                compressed.write(block)
    after = source.stat()
    if (before.st_size, before.st_mtime_ns) != (after.st_size, after.st_mtime_ns):
        raise ValueError(f'Source changed during the build: {source}')
    return {'path': str(source.relative_to(root)), 'bytes': before.st_size, 'sha256': digest.hexdigest()}


def inspect_output(output):
    """Only replace an intact output previously generated by this script."""
    if not output.exists():
        return
    marker = output / REPORT
    if not output.is_dir() or output.is_symlink() or not marker.is_file() or marker.is_symlink():
        raise ValueError(f'Refusing to replace an existing unmanaged output: {output}')
    report = json.loads(marker.read_text())
    if report.get('generator') != GENERATOR:
        raise ValueError(f'Unrecognized output ownership marker: {marker}')
    expected = {record['path']: record for record in report['files']}
    actual, directories = set(), set()
    for path in output.rglob('*'):
        if path.is_symlink():
            raise ValueError(f'Refusing to replace an output containing symlinks: {path}')
        if path.is_file():
            actual.add(path.relative_to(output).as_posix())
        elif path.is_dir():
            directories.add(path.relative_to(output).as_posix())
    expected_dirs = {parent.as_posix() for name in expected for parent in Path(name).parents if str(parent) != '.'}
    if actual != set(expected) | {REPORT} or directories != expected_dirs:
        raise ValueError('Existing output contains added or missing files/directories; choose another output.')
    for name, record in expected.items():
        path = output / name
        if path.stat().st_size != record['bytes'] or sha256(path) != record['sha256']:
            raise ValueError(f'Existing output was modified; refusing to remove: {path}')


def write_report(stage, summary, max_bytes):
    files = [{'path': path.relative_to(stage).as_posix(), 'bytes': path.stat().st_size, 'sha256': sha256(path)}
             for path in sorted(stage.rglob('*')) if path.is_file()]
    payload_bytes = sum(record['bytes'] for record in files)
    report = dict(summary, generator=GENERATOR, files=files, file_count=len(files) + 1,
                  payload_bytes=payload_bytes, total_bytes=0, maximum_bytes=max_bytes)
    # The report includes its own size in totals, but omits its self-referential digest.
    while True:
        text = json_text(report)
        size = payload_bytes + len(text.encode())
        if report['total_bytes'] == size:
            break
        report['total_bytes'] = size
    if size >= max_bytes:
        raise ValueError(f'Site is {size:,} bytes; it must be smaller than {max_bytes:,} bytes.')
    (stage / REPORT).write_text(text)
    return report


def install(stage, output):
    if not output.exists():
        stage.replace(output)
        return
    inspect_output(output)
    backup = Path(tempfile.mkdtemp(prefix=f'.{output.name}-previous-', dir=output.parent))
    backup.rmdir()
    output.replace(backup)
    try:
        stage.replace(output)
    except BaseException:
        backup.replace(output)
        raise
    shutil.rmtree(backup)


def build(root, output, workers=4, max_bytes=MAX_BYTES):
    root = Path(root).resolve()
    requested = Path(output).expanduser()
    if requested.is_symlink():
        raise ValueError('Output must not be a symlink.')
    output = requested.resolve()
    if output.is_relative_to(root) or root.is_relative_to(output):
        raise ValueError('Output must be separate from the source tree and its ancestors.')
    if workers < 1 or max_bytes < 1:
        raise ValueError('workers and maximum bytes must be positive')
    inspect_output(output)
    csv_files = frontend_csv_files(root)
    manifest_path = root / 'data/datasets.json'
    original_manifest = manifest_path.read_bytes()
    manifest = json.loads(original_manifest)
    ready = [entry for entry in manifest['datasets'] if entry['status'] == 'ready']
    paths = [entry['path'] for entry in ready]
    if not ready or len(paths) != len(set(paths)) or any(not re.fullmatch(r'[a-z0-9_-]+/\d{4}', p) for p in paths):
        raise ValueError('Dataset manifest has no ready entries, unsafe paths, or duplicate ready paths.')
    output.parent.mkdir(parents=True, exist_ok=True)
    stage = Path(tempfile.mkdtemp(prefix=f'.{output.name}-building-', dir=output.parent))
    try:
        copy_assets(root, stage)
        jobs = [(root / 'data/processed' / entry['path'] / name,
                 stage / 'data/processed' / entry['path'] / (name + '.gz'), root)
                for entry in ready for name in csv_files]
        with ThreadPoolExecutor(max_workers=workers) as executor:
            inputs = list(executor.map(compress_csv, jobs))
        input_hashes = {record['path']: record['sha256'] for record in inputs}
        for entry in ready:
            entry['compression'] = 'gzip'
            digest = hashlib.sha256()
            for name in csv_files:
                digest.update((name + '\0' + input_hashes[f"data/processed/{entry['path']}/{name}"] + '\0').encode())
            entry['data_version'] = digest.hexdigest()[:16]
        (stage / 'data/datasets.json').write_text(json_text(manifest))
        (stage / '.nojekyll').write_text('')
        release = version_frontend.build(stage)
        if manifest_path.read_bytes() != original_manifest:
            raise ValueError('Dataset manifest changed during build; wait for the batch to finish and retry.')
        report = write_report(stage, {'ready_datasets': len(ready), 'csv_files_per_dataset': csv_files,
                                     'source_csv_bytes': sum(r['bytes'] for r in inputs),
                                     'source_manifest_sha256': hashlib.sha256(original_manifest).hexdigest(),
                                     'browser_release': release}, max_bytes)
        install(stage, output)
        return {key: value for key, value in report.items() if key != 'files'}
    finally:
        if stage.exists():
            shutil.rmtree(stage)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, default=ROOT)
    parser.add_argument('--output', type=Path, required=True, help='Standalone output directory outside the source tree')
    parser.add_argument('--workers', type=int, default=4)
    args = parser.parse_args()
    try:
        print(json_text(build(args.root, args.output, args.workers)))
    except (OSError, ValueError, KeyError) as error:
        print(str(error), file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
